### ISSUE TITLE
Crashes at loading world if ewewukek's Musket Mod is active.

### ISSUE THREAD

**Issue by MatiCugno69** [TheDeathlyCow/thermoo#41]
I have over 300 mods, and the combo Frostiful-Scorchful-Thermoo only works if i remove Musket Mod.

---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-12-29 21:58:36
Description: Ticking entity

java.lang.ClassCastException: class net.minecraft.class_8551 cannot be cast to class net.minecraft.class_52 (net.minecraft.class_8551 and net.minecraft.class_52 are in unnamed module of loader 'knot' @5cb9f472)
	at knot//net.minecraft.class_60.handler$kdf000$musketmod$getElement(class_60.java:2025)
	at knot//net.minecraft.class_60.getElement(class_60.java:102)
	at knot//net.minecraft.class_8489.getElement(class_8489.java:15)
	at knot//net.minecraft.class_4568.method_22579(class_4568.java:47)
	at knot//net.minecraft.class_4568.test(class_4568.java:15)
	at knot//com.github.thedeathlycow.thermoo.api.temperature.effects.ConfiguredTemperatureEffect.testPredicate(ConfiguredTemperatureEffect.java:147)
	at knot//com.github.thedeathlycow.thermoo.api.temperature.effects.ConfiguredTemperatureEffect.applyIfPossible(ConfiguredTemperatureEffect.java:138)
	at knot//net.minecraft.class_1309.handler$opk000$thermoo$tickFreezingEffects(class_1309.java:11623)
	at knot//net.minecraft.class_1309.method_6007(class_1309.java:2735)
	at knot//net.minecraft.class_1308.method_6007(class_1308.java:550)
	at knot//net.minecraft.class_1296.method_6007(class_1296.java:128)
	at knot//net.minecraft.class_1429.method_6007(class_1429.java:58)
	at knot//net.minecraft.class_1428.method_6007(class_1428.java:85)
	at knot//net.minecraft.class_1309.method_5773(class_1309.java:2419)
	at knot//net.minecraft.class_1308.method_5773(class_1308.java:351)
	at knot//net.minecraft.class_3218.observable$track(class_3218.java:23254)
	at knot//net.minecraft.class_3218.redirect$khg000$observable$onTickNonPassenger(class_3218.java:23270)
	at knot//net.minecraft.class_3218.method_18762(class_3218.java:739)
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:480)
	at knot//net.minecraft.class_3218.method_31420(class_3218.java:385)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:353)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:105)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:842)

**Comment by TheDeathlyCow** [comment]
Can you please provide the versions of these mods you are using, I cannot replicate this in 1.21.1.

**Comment by TheDeathlyCow** [comment]
For what it's worth, however, this appears to be an issue with a mixin in the musket mod itself, and not Thermoo or any of my other Thermoo based mods.

**Comment by MatiCugno69** [comment]
yeah sorry i forgot half the important stuff and expected you to give me an answer, sorry about that. im running the latest 1.20.1 version of the mods. I'm gonna go bother the other mod creator, amazing mod! tons of fun!

**Comment by TheDeathlyCow** [comment]
Ok, I think I found the issue. I believe this line of code in the musket mod, which is no longer present in the 1.21 version, is responsible:

https://github.com/ewewukek/mc-musketmod/blob/6b339e6660102675637db5210b77f219e6f60018/fabric/src/main/java/ewewukek/musketmod/mixin/LootDataManagerMixin.java#L25

The crash occurs because the `getReturnValue` method call attempts to cast an instance of `AnyOfLootCondition` to a `LootTable` for some reason (though it's hidden by generics). I don't think Thermoo is doing anything wrong here; this is just some weirdness from the Musket mod. But feel free to reopen if it is.

**Comment by MatiCugno69** [comment]
you're a beast, thank you so much.
